#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#

WX = E:\wxWidgets-3.3.1

WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -I$(WX)\include
CFLAGS = -pipe -mthreads -D__GNUWIN32__ -D__WXMSW__ -DWXUSINGDLL -DwxUSE_UNICODE -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -mthreads

INC_DEBUG = $(INC) -I$(WX)\lib\gcc_dll\mswud
CFLAGS_DEBUG = $(CFLAGS) -g -D__WXDEBUG__
RESINC_DEBUG = $(RESINC) -I$(WX)\lib\gcc_dll\mswud
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L$(WX)\lib\gcc_dll
LIB_DEBUG = $(LIB) -lwxmsw33ud_core -lwxbase33ud
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\DealCppFiles.exe

INC_RELEASE = $(INC) -I$(WX)\lib\gcc_dll\mswu
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC) -I$(WX)\lib\gcc_dll\mswu
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L$(WX)\lib\gcc_dll
LIB_RELEASE = $(LIB) -lwxmsw33u_core -lwxbase33u
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\DealCppFiles.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\DealCppFilesApp.o $(OBJDIR_DEBUG)\\DealCppFilesMain.o $(OBJDIR_DEBUG)\\resource.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\DealCppFilesApp.o $(OBJDIR_RELEASE)\\DealCppFilesMain.o $(OBJDIR_RELEASE)\\resource.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) -mwindows $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\DealCppFilesApp.o: DealCppFilesApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DealCppFilesApp.cpp -o $(OBJDIR_DEBUG)\\DealCppFilesApp.o

$(OBJDIR_DEBUG)\\DealCppFilesMain.o: DealCppFilesMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DealCppFilesMain.cpp -o $(OBJDIR_DEBUG)\\DealCppFilesMain.o

$(OBJDIR_DEBUG)\\resource.o: resource.rc
	$(WINDRES) -i resource.rc -J rc -o $(OBJDIR_DEBUG)\\resource.o -O coff $(INC_DEBUG)

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\DealCppFilesApp.o: DealCppFilesApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DealCppFilesApp.cpp -o $(OBJDIR_RELEASE)\\DealCppFilesApp.o

$(OBJDIR_RELEASE)\\DealCppFilesMain.o: DealCppFilesMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DealCppFilesMain.cpp -o $(OBJDIR_RELEASE)\\DealCppFilesMain.o

$(OBJDIR_RELEASE)\\resource.o: resource.rc
	$(WINDRES) -i resource.rc -J rc -o $(OBJDIR_RELEASE)\\resource.o -O coff $(INC_RELEASE)

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

